default: &default
  adapter: postgresql
  encoding: unicode
  user: cairian
  password: 123456
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: api_development